Repository Tanmaydeep-Singh/HF25, pull requests merged in 2025-10, with the labels that each got.

#1 Update README.md for the new HF25 guidlines
  README.md
Labels: documentation, Hacktober-accepted, Non-tech

#4 HF25: Bot added a tracking-bot
  bot/tracking-bot/core/__pycache__/document_parser.cpython-311.pyc
  bot/tracking-bot/core/__pycache__/progress_tracker.cpython-311.pyc
  bot/tracking-bot/core/__pycache__/repo_connector.cpython-311.pyc
  bot/tracking-bot/core/__pycache__/report_generator.cpython-311.pyc
  bot/tracking-bot/core/__pycache__/task_extractor.cpython-311.pyc
  bot/tracking-bot/core/document_parser.py
  bot/tracking-bot/core/progress_tracker.py
  bot/tracking-bot/core/repo_connector.py
  bot/tracking-bot/core/report_generator.py
  bot/tracking-bot/core/task_extractor.py
  bot/tracking-bot/main.py
  bot/tracking-bot/models/__pycache__/task.cpython-311.pyc
  bot/tracking-bot/models/task.py
  bot/tracking-bot/requirements.txt
Labels: hacktoberfest-accepted

#9 login signUp page added
  web/custome-chrome-tab/Login-Sign-up-page/app.js
  web/custome-chrome-tab/Login-Sign-up-page/index.html
  web/custome-chrome-tab/Login-Sign-up-page/style.css
Labels: Hacktober-accepted, Tech, hacktoberfest-accepted
